# Site
name: "Spatial Biology Association"
title: "Spatial Biology Association"
description: <a style="color:black; href="https://ajitjohnson.com/">Spatial Biology Association</a>
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /sba
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: ajitjohsnon.n@gmail.com

# Authors
authors:
  ajit:
    name: Ajit Johnson Nirmal
    display_name: Ajit Nirmal
    avatar: 'assets/images/authors/ajit.png'
    email: ajitjohsnon.n@gmail.com
    web: https://ajitjohnson.com/
    twitter: https://twitter.com/ajitjohnson_n
    description: Cancer Geneticist @harvard
  clarence:
    name: Clarence Yapp
    display_name: Clarence Yapp
    avatar: 'assets/images/authors/clarence.png'
    email: clarence@hms.harvard.edu
    web: https://scholar.harvard.edu/clarence/who-clarence
    twitter: https://twitter.com/
    description: Director of Microscopy and Image Analysis at the Laboratory of Systems Pharmacology (LSP).
  maren:
    name: Maren Pein
    display_name: Maren Pein
    avatar: 'assets/images/authors/maren.png'
    email: mpein@hs.uci.edu
    web: https://orcid.org/0000-0002-7906-5960
    twitter: https://twitter.com/maren_pein
    description: Postdoctoral Researcher at UC Irvine with expertise in breast cancer, microenvironment and metastasis.
  sandhya:
    name: Sandhya Prabhakaran
    display_name: Sandhya Prabhakaran
    avatar: 'assets/images/authors/sandhya.png'
    email: sandhyaprabhakaran@gmail.com
    web: http://sandhyaprabhakaran.com/
    twitter: https://twitter.com/sandhya212
    description: Applied Research Scientist with Dr. Alexander Anderson at the Integrated Mathematical Oncology Department, Moffitt Cancer Centre.
  charley:
    name: Charley Xi
    display_name: Charley Xi
    avatar: 'assets/images/avatar-sal.png'
    email: zxi1@bu.edu
    web: https://www.bumc.bu.edu/compbiomed/people/post-doctorates/
    twitter: https://twitter.com/
    description: Grad student at Molecular and Translational Medicine- faculty mentor Sarah Mazzilli,  Jennifer Beane
  angela:
    name: Angela Kruse
    display_name: Angela Kruse
    avatar: 'assets/images/authors/angela.png'
    email: angela.kruse@vanderbilt.edu
    web: https://medschool.vanderbilt.edu/msrc/person/643/
    twitter: https://twitter.com/arkannie
    description: Postdoctoral Fellow at Vanderbilt University. Interested in insect disease vectors, proteomics, imaging mass spectrometry.

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
