# Site
name: "VIM - Visualization and Image Data Management"
title: "Visualization and Image Data Management"
description: <a href="/sba" style="color:black">Visualization and Image Data Management</a>
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /website
google_analytics: 'G-EBSP79RQR7'
disqus: 'website'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: krueger@g.harvard.edu

# Authors
authors:
  robert:
    name: Robert Krueger
    display_name: Robert Krueger
    avatar: 'assets/images/authors/robert.png'
    email: krueger@g.harvard.edu
    web: https://kruegert.github.io/
    twitter: https://mobile.twitter.com/robertk_vis
    description: Postdoctoral Research Scientist for biomedical visualization and visual analytics at Visual Computing Group (VCG) and Laboratory of Systems Pharmacology (LSP) @Harvard.

  allison:
    name: Allison Maier
    display_name: Allison Maier
    avatar: 'assets/images/authors/robert.png'
    email: krueger@g.harvard.edu
    web: https://kruegert.github.io/
    twitter: https://mobile.twitter.com/robertk_vis
    description: Postdoctoral Research Scientist for biomedical visualization and visual analytics at Visual Computing Group (VCG) and Laboratory of Systems Pharmacology (LSP) @Harvard.
    
   mark:
    name: Mark Keller
    display_name: Mark Keller
    avatar: 'assets/images/authors/robert.png'
    email: krueger@g.harvard.edu
    web: https://kruegert.github.io/
    twitter: https://mobile.twitter.com/robertk_vis
    description: Postdoctoral Research Scientist for biomedical visualization and visual analytics at Visual Computing Group (VCG) and Laboratory of Systems Pharmacology (LSP) @Harvard.   

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 8
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
